# Lecture 8

## Install external dependencies

In [1]:
!uv add numpy

Resolved 96 packages in 282ms
Prepared 1 package in 606ms
Installed 1 package in 35ms
 + numpy==2.4.4

In [2]:
!uv add pandas

Resolved 97 packages in 102ms
Prepared 1 package in 566ms
Installed 1 package in 40ms
 + pandas==3.0.2

In [3]:
!uv add matplotlib

Resolved 104 packages in 254ms
Prepared 7 packages in 773ms
Installed 7 packages in 14ms
 + contourpy==1.3.3
 + cycler==0.12.1
 + fonttools==4.62.1
 + kiwisolver==1.5.0
 + matplotlib==3.10.8
 + pillow==12.2.0
 + pyparsing==3.3.2

## numpy example

In [5]:
import numpy

In [7]:
#dir(numpy)

a subpackage for Linear Algebra `numpy.linalg`

In [8]:
dir(numpy.linalg)

['LinAlgError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_linalg',
 '_umath_linalg',
 'cholesky',
 'cond',
 'cross',
 'det',
 'diagonal',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'lstsq',
 'matmul',
 'matrix_norm',
 'matrix_power',
 'matrix_rank',
 'matrix_transpose',
 'multi_dot',
 'norm',
 'outer',
 'pinv',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'svdvals',
 'tensordot',
 'tensorinv',
 'tensorsolve',
 'test',
 'trace',
 'vecdot',
 'vector_norm']

In [10]:
help(numpy.linalg.solve)

Help on method descriptor solve in module numpy.linalg:

solve(a, b)
    Solve a linear matrix equation, or system of linear scalar equations.

    Computes the "exact" solution, `x`, of the well-determined, i.e., full
    rank, linear matrix equation `ax = b`.

    Parameters
    ----------
    a : (..., M, M) array_like
        Coefficient matrix.
    b : {(M,), (..., M, K)}, array_like
        Ordinate or "dependent variable" values.

    Returns
    -------
    x : {(..., M,), (..., M, K)} ndarray
        Solution to the system a x = b.  Returned shape is (..., M) if b is
        shape (M,) and (..., M, K) if b is (..., M, K), where the "..." part is
        broadcasted between a and b.

    Raises
    ------
    LinAlgError
        If `a` is singular or not square.

    See Also
    --------
    scipy.linalg.solve : Similar function in SciPy.

    Notes
    -----
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.

    The solutions are computed using LAPACK routine ``_gesv``.

    `a` must be square and of full-rank, i.e., all rows (or, equivalently,
    columns) must be linearly independent; if either is not true, use
    `lstsq` for the least-squares best "solution" of the
    system/equation.

    .. versionchanged:: 2.0

       The b array is only treated as a shape (M,) column vector if it is
       exactly 1-dimensional. In all other instances it is treated as a stack
       of (M, K) matrices. Previously b would be treated as a stack of (M,)
       vectors if b.ndim was equal to a.ndim - 1.

    References
    ----------
    .. [1] G. Strang, *Linear Algebra and Its Applications*, 2nd Ed., Orlando,
           FL, Academic Press, Inc., 1980, pg. 22.

    Examples
    --------
    Solve the system of equations:
    ``x0 + 2 * x1 = 1`` and
    ``3 * x0 + 5 * x1 = 2``:

    >>> import numpy as np
    >>> a = np.array([[1, 2], [3, 5]])
    >>> b = np.array([1, 2])
    >>> x = np.linalg.solve(a, b)
    >>> x
    array([-1.,  1.])

    Check that the solution is correct:

    >>> np.allclose(np.dot(a, x), b)
    True

### `numpy.solve`
The `solve` functions solves systems of linear equation - a common problem in science

In [12]:
numpy.linalg.solve([[3, 0, 0], [1, 8, 0], [0, 4, -2]], [30, 18, 2])

array([10.,  1.,  1.])

In [13]:
%%file data.txt
1 2 3
4 5 6
7 8 9

Overwriting data.txt

In [16]:
matrix = numpy.loadtxt('data.txt')
matrix

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

### referencing parts of the array

In [18]:
matrix[0] # the first row

array([1., 2., 3.])

In [21]:
matrix[0][0] # list-like indexing

np.float64(1.0)

In [22]:
matrix[0, 0]

np.float64(1.0)

In [23]:
matrix[:2, :2 ]  # upper left corner of dim 2

array([[1., 2.],
       [4., 5.]])

In [24]:
matrix[:, -1] # the last column

array([3., 6., 9.])

### matrix muliplication

Straight forward looping is slow in Python and scales as $N^3$

In [34]:
import time

n = 512
a = numpy.ones((n, n))
b = numpy.ones((n, n))
c = numpy.zeros((n, n))
t1 = time.time()
for i in range(n):
    for j in range(n):
        for k in range(n):
            c[i, j] += a[i, k]*b[k, j]
t2 = time.time()
print("Loop timing", t2-t1)
print(c)

Loop timing 124.27959299087524
[[512. 512. 512. ... 512. 512. 512.]
 [512. 512. 512. ... 512. 512. 512.]
 [512. 512. 512. ... 512. 512. 512.]
 ...
 [512. 512. 512. ... 512. 512. 512.]
 [512. 512. 512. ... 512. 512. 512.]
 [512. 512. 512. ... 512. 512. 512.]]

The numpy implementation uses highly optimized code

In [36]:
t1 = time.time()
c = a @ b
t2 = time.time()
print("dot timing", t2-t1)
print(c)

dot timing 0.006704807281494141
[[512. 512. 512. ... 512. 512. 512.]
 [512. 512. 512. ... 512. 512. 512.]
 [512. 512. 512. ... 512. 512. 512.]
 ...
 [512. 512. 512. ... 512. 512. 512.]
 [512. 512. 512. ... 512. 512. 512.]
 [512. 512. 512. ... 512. 512. 512.]]

## Pandas
Python's main library for handling tabular data

### Series
Like labeled one-dimensional arrays

In [2]:
# Pandas series
import pandas as pd

In [39]:
s = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})

#### Pandas arithmetics

In [40]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [41]:
s + s

a    2
b    4
c    6
d    8
dtype: int64

In [42]:
s + 2

a    3
b    4
c    5
d    6
dtype: int64

In [43]:
s * 100

a    100
b    200
c    300
d    400
dtype: int64

#### selecting elements and slicing

In [44]:
selection = ['a', 'c']

In [45]:
s[selection]

a    1
c    3
dtype: int64

In [46]:
s['a': 'c']

a    1
b    2
c    3
dtype: int64

In [47]:
s > 2

a    False
b    False
c     True
d     True
dtype: bool

In [48]:
s[s > 2] # filter all values which are greatar than 2

c    3
d    4
dtype: int64

In [50]:
# dir(s) what is defined for Series?

In [51]:
s.mean()

np.float64(2.5)

In [52]:
s[s > 2].mean()

np.float64(3.5)

In [53]:
s.describe()

count    4.000000
mean     2.500000
std      1.290994
min      1.000000
25%      1.750000
50%      2.500000
75%      3.250000
max      4.000000
dtype: float64

### dataframes

In [55]:
data = {'country': ['Belgium', 'France', 'Germany', 'Netherlands', 'United Kingdom'],
       'population': [11.3, 64.3, 81.3, 16.9, 64.9],
       'area': [30510, 671308, 357050, 41526, 244820],
       'capital': ['Brussels', 'Paris', 'Berlin', 'Amsterdam', 'London']}

In [57]:
df = pd.DataFrame(data)

In [58]:
df

          country  population    area    capital
0         Belgium        11.3   30510   Brussels
1          France        64.3  671308      Paris
2         Germany        81.3  357050     Berlin
3     Netherlands        16.9   41526  Amsterdam
4  United Kingdom        64.9  244820     London

In [59]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [60]:
df.columns

Index(['country', 'population', 'area', 'capital'], dtype='str')

In [62]:
df.dtypes

country           str
population    float64
area            int64
capital           str
dtype: object

In [63]:
df.values

array([['Belgium', 11.3, 30510, 'Brussels'],
       ['France', 64.3, 671308, 'Paris'],
       ['Germany', 81.3, 357050, 'Berlin'],
       ['Netherlands', 16.9, 41526, 'Amsterdam'],
       ['United Kingdom', 64.9, 244820, 'London']], dtype=object)

In [64]:
df

          country  population    area    capital
0         Belgium        11.3   30510   Brussels
1          France        64.3  671308      Paris
2         Germany        81.3  357050     Berlin
3     Netherlands        16.9   41526  Amsterdam
4  United Kingdom        64.9  244820     London

In [67]:
df = df.set_index('country')

In [68]:
df

                population    area    capital
country
Belgium               11.3   30510   Brussels
France                64.3  671308      Paris
Germany               81.3  357050     Berlin
Netherlands           16.9   41526  Amsterdam
United Kingdom        64.9  244820     London

In [71]:
df['population'] / df['area'] * 1000

country
Belgium           0.370370
France            0.095783
Germany           0.227699
Netherlands       0.406974
United Kingdom    0.265093
dtype: float64

In [72]:
df['population_density'] = df['population'] / df['area'] * 1000

In [73]:
df

                population    area    capital  population_density
country
Belgium               11.3   30510   Brussels            0.370370
France                64.3  671308      Paris            0.095783
Germany               81.3  357050     Berlin            0.227699
Netherlands           16.9   41526  Amsterdam            0.406974
United Kingdom        64.9  244820     London            0.265093

In [75]:
df.sort_index()

                population    area    capital  population_density
country
Belgium               11.3   30510   Brussels            0.370370
France                64.3  671308      Paris            0.095783
Germany               81.3  357050     Berlin            0.227699
Netherlands           16.9   41526  Amsterdam            0.406974
United Kingdom        64.9  244820     London            0.265093

In [76]:
df.sort_values('population')

                population    area    capital  population_density
country
Belgium               11.3   30510   Brussels            0.370370
Netherlands           16.9   41526  Amsterdam            0.406974
France                64.3  671308      Paris            0.095783
United Kingdom        64.9  244820     London            0.265093
Germany               81.3  357050     Berlin            0.227699

In [77]:
df.sort_values('population', ascending=False)

                population    area    capital  population_density
country
Germany               81.3  357050     Berlin            0.227699
United Kingdom        64.9  244820     London            0.265093
France                64.3  671308      Paris            0.095783
Netherlands           16.9   41526  Amsterdam            0.406974
Belgium               11.3   30510   Brussels            0.370370

In [78]:
df.sort_values('population', ascending=False).head(2) # data for the two countries with highest poplation

                population    area capital  population_density
country
Germany               81.3  357050  Berlin            0.227699
United Kingdom        64.9  244820  London            0.265093